---
# AWS Vault Configuration
- name: Validate AWS Vault configuration
  assert:
    that:
      - aws_profiles is defined
      - aws_profiles | length > 0
      - aws_sso_session_name is defined
      - aws_sso_region is defined
      - aws_sso_start_url is defined
    fail_msg: |
      AWS Vault configuration is incomplete. Please ensure the following are defined in config.yml:
      - aws_profiles (list of profiles)
      - aws_sso_session_name (SSO session name)
      - aws_sso_region (SSO region)
      - aws_sso_start_url (SSO start URL)
    success_msg: "AWS Vault configuration validation passed"

- name: Check if AWS config directory exists
  stat:
    path: ~/.aws
  register: aws_dir_check

- name: Ensure AWS config directory exists
  file:
    path: ~/.aws
    state: directory
    mode: '0755'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
  register: aws_dir_created

- name: Configure AWS config file
  template:
    src: aws-config.j2
    dest: ~/.aws/config
    mode: '0600'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    backup: yes
  register: aws_config_created

- name: Display AWS Vault configuration summary
  debug:
    msg: |
      AWS Vault configuration completed:
      - SSO Region: {{ aws_sso_region }}
      - SSO Start URL: {{ aws_sso_start_url }}
      - Configured profiles: {{ aws_profiles | map(attribute='name') | list }}
      - Config file: {{ 'Created' if aws_config_created.changed else 'Already exists' }}
      {% if aws_config_created.backup_file is defined %}
      - Previous config backed up to: {{ aws_config_created.backup_file }}
      {% endif %}
      
      To use AWS Vault with these profiles:
      {% for profile in aws_profiles %}
      - aws-vault exec {{ profile.name }} -- aws s3 ls
      {% endfor %} 